### ISSUE TITLE
items on taskbar are not included

### ISSUE THREAD

**Issue by MartinIsti** [JochenBaier/fastwindowswitcher#4]
I started using FastWindowSwitcher with my previous laptop and it worked fine, it really made life smoother! I really appreciate your work for making it available for us, users! Then my laptop broke completely and I had it replaced with a new one. Same Windows 8.1 OS and when I run FastWindowSwitcher and press the key-combo it only works on the windows that are on the desktop but it doesn't on the ones that are in the taskbar as per below screenshot. I tried to hunt for other people having this problem if they might have a solution for it but no luck so far.
![image](https://user-images.githubusercontent.com/4967918/32351528-8f953b00-c082-11e7-926c-15108c2b32bd.png)
I hope there is a quick & easy solution for it that doesn't require too much troubleshooting and coding for you!
Thanks in advance!

**Comment by JochenBaier** [comment]
I will try to reproduce it after installing Windows 8.1 in a  virtual machine.
Does it work if the taskbar is at horizontal position on the bottom of the desktop?

**Comment by MartinIsti** [comment]
Thanks for having a look, Jochen!

I've tested on another machine (still Win 8.1) and this time with the default taskbar position (horizontal, bottom) and the same happens.

**Comment by JochenBaier** [comment]
I uploaded a fixed version for testing: 
http://www.jochen-baier.de/fastwindowswitcher/FastWindowSwitcher_02100.zip. 
If you find time please let me know if it is working.

**Comment by MartinIsti** [comment]
It works now! I tried on both of my Win 8.1 machines and it's already made my day :)

Thanks for having a look and fixing it so quickly!
